# Generated by Django 4.0.4 on 2022-06-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_todo_work_status_alter_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Work_Status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
